apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: nginx

spec:
  minReplicas: 3
  maxReplicas: 12
  selector:
    matchLabels:
      app: nginx
      
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
